apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "saltstack.master.fullname" . }}
  labels:
    {{- include "saltstack.master.labels" . | nindent 4 }}
data:
  master.conf: |
    {
      "user": "salt",
      "fileserver_backend": [
        "gitfs"
      ],
      "gitfs_provider": "pygit2",
      "gitfs_remotes": {{ toJson .Values.master.config.gitfs_remotes }},
      {{- if .Values.master.config.ext_pillar }}
      "ext_pillar": {{ toJson .Values.master.config.ext_pillar }},
      {{- end }}
      "gitfs_update_interval": 60,
      "log_level": "{{ .Values.master.config.log_level }}"
    }
