apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saltstack.master.fullname" . }}
  labels:
    {{- include "saltstack.master.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.master.replicaCount }}
  selector:
    matchLabels:
      {{- include "saltstack.master.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.master.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "saltstack.master.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.master.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "saltstack.master.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.master.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-master
          securityContext:
            {{- toYaml .Values.master.securityContext | nindent 12 }}
          image: "{{ .Values.master.image.repository }}:{{ .Values.master.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.master.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: salt-pub
              containerPort: 4505
              protocol: TCP
            - name: salt-req
              containerPort: 4506
              protocol: TCP
          resources:
            {{- toYaml .Values.master.resources | nindent 12 }}
      {{- with .Values.master.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.master.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.master.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
