apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "saltstack.master.fullname" . }}
  labels:
    {{- include "saltstack.master.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.master.replicaCount }}
  selector:
    matchLabels:
      {{- include "saltstack.master.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.master.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "saltstack.master.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.master.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "saltstack.master.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.master.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-master
          securityContext:
            {{- toYaml .Values.master.securityContext | nindent 12 }}
          image: "{{ .Values.master.image.repository }}:{{ .Values.master.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.master.image.pullPolicy }}
          env:
            - name: SALT_MASTER_CONFIG
              valueFrom:
                configMapKeyRef:
                  name: {{ include "saltstack.master.fullname" . }}
                  key: master.conf
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
            - name: publish
              containerPort: 4505
              protocol: TCP
            - name: return
              containerPort: 4506
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTPS
            failureThreshold: 1
            periodSeconds: 10
          startupProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTPS
            failureThreshold: 10
            periodSeconds: 10
          resources:
            {{- toYaml .Values.master.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.master.persistence.name }}
              mountPath: {{ .Values.master.persistence.path }}
              {{- if .Values.master.persistence.subPath }}
              subPath: {{ .Values.master.persistence.subPath }}
              {{- end }}
      {{- with .Values.master.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.master.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.master.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Values.master.persistence.name }}
          {{- if .Values.master.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ default (include "saltstack.master.fullname" .) .Values.master.persistence.existingClaim }}
          {{- else }}
          emptyDir: {}
          {{- end }}
