apiVersion: v1
kind: Service
metadata:
  name: {{ include "saltstack.master.fullname" . }}
  labels:
    {{- include "saltstack.master.labels" . | nindent 4 }}
spec:
  type: {{ .Values.master.service.type }}
  ports:
    - port: {{ .Values.master.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 4505
      targetPort: salt-pub
      protocol: TCP
      name: salt-pub
    - port: 4506
      targetPort: salt-req
      protocol: TCP
      name: salt-req
  selector:
    {{- include "saltstack.master.selectorLabels" . | nindent 4 }}
