{{- if .Values.master.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "saltstack.master.serviceAccountName" . }}
  labels:
    {{- include "saltstack.master.labels" . | nindent 4 }}
  {{- with .Values.master.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
